name: pre-commit

on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - run: |
          sudo apt update
          sudo apt install -y gettext

      - run: dpkg-query -L gettext

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - uses: pre-commit/action@v3.0.1
